"""add_audit_columns_to_user_roles

Revision ID: a9facb9ee02f
Revises: b5ea35f03526
Create Date: 2026-01-26 06:38:02.489406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9facb9ee02f'
down_revision: Union[str, None] = 'b5ea35f03526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    op.alter_column('field_type_definitions', 'strict_type_checking',
               existing_type=sa.BOOLEAN(),
               comment='Whether to enforce strict data type validation',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('form_submissions', 'submitted_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username of submitter (replaces fieldman_id)',
               existing_nullable=True)
    op.alter_column('form_submissions', 'reviewed_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username of reviewer (approval/rejection)',
               existing_nullable=True)
    op.alter_column('form_submissions', 'validated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username who validated/approved',
               existing_nullable=True)
    op.alter_column('form_submissions', 'validated_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of validation/approval',
               existing_nullable=True)
    op.create_index(op.f('ix_form_submissions_submitted_by'), 'form_submissions', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_form_submissions_validated_by'), 'form_submissions', ['validated_by'], unique=False)
    op.create_index(op.f('ix_form_submissions_validated_on'), 'form_submissions', ['validated_on'], unique=False)
    op.alter_column('roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username of creator',
               existing_nullable=True)
    op.alter_column('roles', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username of last updater',
               existing_nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Username of user who last updated this record',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username of user who last updated this record',
               existing_nullable=True)
    op.alter_column('roles', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username of last updater',
               existing_nullable=True)
    op.alter_column('roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username of creator',
               existing_nullable=True)
    op.drop_index(op.f('ix_form_submissions_validated_on'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_validated_by'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_submitted_by'), table_name='form_submissions')
    op.alter_column('form_submissions', 'validated_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of validation/approval',
               existing_nullable=True)
    op.alter_column('form_submissions', 'validated_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username who validated/approved',
               existing_nullable=True)
    op.alter_column('form_submissions', 'reviewed_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username of reviewer (approval/rejection)',
               existing_nullable=True)
    op.alter_column('form_submissions', 'submitted_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Username of submitter (replaces fieldman_id)',
               existing_nullable=True)
    op.alter_column('field_type_definitions', 'strict_type_checking',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether to enforce strict data type validation',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey')
    )
    # ### end Alembic commands ###
