"""add_departments_and_locations_tables

Revision ID: 69ec3f6c799f
Revises: e9d1e841d767
Create Date: 2026-01-30 02:15:27.595361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69ec3f6c799f'
down_revision: Union[str, None] = 'e9d1e841d767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    op.alter_column('field_type_definitions', 'strict_type_checking',
               existing_type=sa.BOOLEAN(),
               comment='Whether to enforce strict data type validation',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_file_uploads_field_id', table_name='file_uploads')
    op.drop_index('ix_file_uploads_submission_field', table_name='file_uploads')
    op.create_foreign_key(None, 'file_uploads', 'form_submissions', ['submission_id'], ['id'])
    op.create_foreign_key(None, 'form_field_mappings', 'form_templates', ['template_id'], ['id'])
    op.drop_index('ix_form_submissions_created_at', table_name='form_submissions')
    op.drop_index('ix_form_submissions_status_created', table_name='form_submissions')
    op.drop_index('ix_form_submissions_submitted_by_status', table_name='form_submissions')
    op.drop_index('ix_form_submissions_template_status', table_name='form_submissions')
    op.drop_index('ix_form_templates_bank_active', table_name='form_templates')
    op.drop_index('ix_form_templates_form_type', table_name='form_templates')
    op.drop_index('ix_roles_created_by', table_name='roles')
    op.drop_index('ix_roles_updated_by', table_name='roles')
    op.drop_column('user_roles', 'created_by')
    op.drop_column('user_roles', 'updated_by')
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'updated_at')
    op.drop_index('ix_users_updated_by', table_name='users')
    op.create_foreign_key(None, 'users', 'banks', ['bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('ix_users_updated_by', 'users', ['updated_by'], unique=False)
    op.add_column('user_roles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_roles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_roles', sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_roles', sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_roles_updated_by', 'roles', ['updated_by'], unique=False)
    op.create_index('ix_roles_created_by', 'roles', ['created_by'], unique=False)
    op.create_index('ix_form_templates_form_type', 'form_templates', ['form_type'], unique=False)
    op.create_index('ix_form_templates_bank_active', 'form_templates', ['bank_id', 'active'], unique=False)
    op.create_index('ix_form_submissions_template_status', 'form_submissions', ['template_id', 'status'], unique=False)
    op.create_index('ix_form_submissions_submitted_by_status', 'form_submissions', ['submitted_by', 'status'], unique=False)
    op.create_index('ix_form_submissions_status_created', 'form_submissions', ['status', 'created_at'], unique=False)
    op.create_index('ix_form_submissions_created_at', 'form_submissions', ['created_at'], unique=False)
    op.drop_constraint(None, 'form_field_mappings', type_='foreignkey')
    op.drop_constraint(None, 'file_uploads', type_='foreignkey')
    op.create_index('ix_file_uploads_submission_field', 'file_uploads', ['submission_id', 'field_id'], unique=False)
    op.create_index('ix_file_uploads_field_id', 'file_uploads', ['field_id'], unique=False)
    op.alter_column('field_type_definitions', 'strict_type_checking',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether to enforce strict data type validation',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey')
    )
    # ### end Alembic commands ###
